In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [6]:
# Importing the dataset
dataset = pd.read_csv('/kaggle/input/chum-modelling-df/Churn_Modelling.csv')
dataset = dataset.loc[:5000]
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [7]:
dataset

RowNumber  CustomerId     Surname  CreditScore Geography  Gender  Age  \
0             1    15634602    Hargrave          619    France  Female   42   
1             2    15647311        Hill          608     Spain  Female   41   
2             3    15619304        Onio          502    France  Female   42   
3             4    15701354        Boni          699    France  Female   39   
4             5    15737888    Mitchell          850     Spain  Female   43   
...         ...         ...         ...          ...       ...     ...  ...   
4996       4997    15620341     Nwebube          500   Germany    Male   44   
4997       4998    15613886    Trevisan          722     Spain    Male   43   
4998       4999    15792916  Ositadimma          559     Spain  Female   40   
4999       5000    15710408  Cunningham          584     Spain  Female   38   
5000       5001    15598695      Fields          834   Germany  Female   68   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
4996       9  160838.13              2          1               0   
4997       1       0.00              1          1               0   
4998       7  144470.77              1          1               1   
4999       3       0.00              2          1               1   
5000       9  130169.27              2          0               1   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
4996        196261.64       0  
4997         44560.17       1  
4998         18917.95       0  
4999          4525.40       0  
5000         93112.20       0  

[5001 rows x 14 columns]

In [8]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [559 'Spain' 'Female' ... 1 1 18917.95]
 [584 'Spain' 'Female' ... 1 1 4525.4]
 [834 'Germany' 'Female' ... 0 1 93112.2]]


In [9]:
print(y)

[1 0 1 ... 0 0 0]


In [10]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = ColumnTransformer([('one_hot_encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X = onehotencoder.fit_transform(X)
X = X[:, 1:]

In [11]:
print(X)

[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 1.0 608 ... 0 1 112542.58]
 [0.0 0.0 502 ... 1 0 113931.57]
 ...
 [0.0 1.0 559 ... 1 1 18917.95]
 [0.0 1.0 584 ... 1 1 4525.4]
 [1.0 0.0 834 ... 0 1 93112.2]]


In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Now let's make the ANN!

In [14]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

2024-06-10 11:22:29.961060: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-10 11:22:29.961224: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-10 11:22:30.127949: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [15]:
# Initialising the ANN
classifier = Sequential()

In [16]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 10)

Epoch 1/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.7773 - loss: 0.6282
Epoch 2/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7907 - loss: 0.4413
Epoch 3/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7962 - loss: 0.4225
Epoch 4/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7908 - loss: 0.4151
Epoch 5/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7944 - loss: 0.4142
Epoch 6/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8054 - loss: 0.4195
Epoch 7/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8303 - loss: 0.4058
Epoch 8/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8247 - loss: 0.4022
Epoch 9/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8181 - loss: 0.4063
Epoch 10/10
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8248 - loss: 0.3928


Making predictions and evaluating the model

In [18]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred_ = (y_pred > 0.5)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [19]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_)

In [20]:
cm

array([[779,  17],
       [142,  63]])

In [21]:
y_test

array([0, 0, 0, ..., 1, 0, 0])

In [22]:
y_pred_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [23]:
y_pred

array([[0.04122805],
       [0.01512226],
       [0.08484314],
       ...,
       [0.3704083 ],
       [0.16207545],
       [0.03821676]], dtype=float32)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred_)
print("Confusion Matrix:\n", cm)

# Menghitung metrik performa
accuracy = accuracy_score(y_test, y_pred_)
precision = precision_score(y_test, y_pred_)
recall = recall_score(y_test, y_pred_)
f1 = f1_score(y_test, y_pred_)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)


Confusion Matrix:
 [[779  17]
 [142  63]]
Accuracy: 0.8411588411588412
Precision: 0.7875
Recall: 0.3073170731707317
F1 Score: 0.4421052631578948
